export const ORDER_REQUEST = 'ORDER_REQUEST'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAIL = 'ORDER_FAIL'
export const ORDER_RESET = 'ORDER_RESET'

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export const ORDER_USER_REQUEST ='ORDER_USER_REQUEST'
export const ORDER_USER_SUCCESS ='ORDER_USER_SUCCESS'
export const ORDER_USER_FAIL ='ORDER_USER_FAIL'