export const SIGN_IN_REQUEST    =   'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS    =   'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL    =   'SIGN_IN_FAIL';
export const SIGN_OUT   =   'SIGN_OUT';


export const SIGN_UP_REQUEST    =   'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS    =   'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL    =   'SIGN_UP_FAIL';

export const USER_DETAILS_REQUEST     ='USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS     ='USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL     ='USER_DETAILS_FAIL'

export const UPDATE_REQUEST ='UPDATE_REQUEST'
export const UPDATE_SUCCESS ='UPDATE_SUCCESS'
export const UPDATE_FAIL ='UPDATE_FAIL'
export const UPDATE_RESET ='UPDATE_RESET'

export const CONFIRMATION_REQUEST ='CONFIRMATION_REQUEST'
export const CONFIRMATION_SUCCESS ='CONFIRMATION_SUCCESS'
export const CONFIRMATION_FAIL ='CONFIRMATION_FAIL'