export const CART_ADD_ITEMS='CART_ADD_ITEMS';
export const    CART_DELETE_ITEM    =   'CART_DELETE_ITEM'

export const SHIPPING_ADDRESS = 'SHIPPING_ADDRESS'

export const PAYMENT_METHOD = 'PAYMENT_METHOD'

export const CART_EMPTY =   'CART_EMPTY'